### ISSUE TITLE
auth.js library not working it has an error

### ISSUE THREAD

**Issue by Mujtabaomar111** [nextauthjs/cli#11]
### Environment

Build Error

Failed to compile
Next.js (14.2.5)
./node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!doctype html>
| <html>
| <head>

This error occurred during the build process and can only be dismissed by fixing the error.

### Describe the issue

i have created new next js typecript with prisma orm other requred packages, and i have followed the auth.js guide to make authentication system using credential provider in auth.js library i am facing the bellow error, but when i delete api route which is in guide of auth.js library the error solved but i still need the authentication using credentials, here this is the error which i am facing to it
Build Error

Failed to compile
Next.js (14.2.5)
./node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!doctype html>
| <html>
| <head>

This error occurred during the build process and can only be dismissed by fixing the error.

### How to reproduce

Build Error

Failed to compile
Next.js (14.2.5)
./node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!doctype html>
| <html>
| <head>

This error occurred during the build process and can only be dismissed by fixing the error.

### Expected behavior

Build Error

Failed to compile
Next.js (14.2.5)
./node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!doctype html>
| <html>
| <head>

This error occurred during the build process and can only be dismissed by fixing the error.

**Comment by balazsorban44** [comment]
Without a reproduction or seeing where this happened, it's hard to debug. If you can provide the repo where you ran a command, please open a new report, and I am happy to look into it more! :green_heart:

**Comment by balazsorban44** [comment]
You might have wanted to open this in https://github.com/nextauthjs/next-auth actually.
