### ISSUE TITLE
npx auth secret has an error and is missing Zod

### ISSUE THREAD

**Issue by mdodell** [nextauthjs/cli#13]
### Environment

  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 75.47 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 4.3.1 - ~/.nvm/versions/node/v18.18.2/bin/yarn
    npm: 10.3.0 - ~/.nvm/versions/node/v18.18.2/bin/npm
  Browsers:
    Chrome: 127.0.6533.120
    Safari: 17.2.1
  npmPackages:
    next: 14.2.4 => 14.2.4 
    next-auth: ^5.0.0-beta.20 => 5.0.0-beta.20 
    react: 18.3.1 => 18.3.1 

### Describe the issue

Running `npx auth secret` results in the following error:

```
node:internal/modules/cjs/loader:1077
  const err = new Error(message);
              ^

Error: Cannot find module 'zod'
Require stack:
- /Users/mdodell/.npm/_npx/cec068fea869db4d/node_modules/@inkeep/ai-api/lib/base64.js
- /Users/mdodell/.npm/_npx/cec068fea869db4d/node_modules/@inkeep/ai-api/lib/encodings.js
- /Users/mdodell/.npm/_npx/cec068fea869db4d/node_modules/@inkeep/ai-api/lib/sdks.js
- /Users/mdodell/.npm/_npx/cec068fea869db4d/node_modules/@inkeep/ai-api/sdk/sdk.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/mdodell/.npm/_npx/cec068fea869db4d/node_modules/@inkeep/ai-api/lib/base64.js:30:24)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mdodell/.npm/_npx/cec068fea869db4d/node_modules/@inkeep/ai-api/lib/base64.js',
    '/Users/mdodell/.npm/_npx/cec068fea869db4d/node_modules/@inkeep/ai-api/lib/encodings.js',
    '/Users/mdodell/.npm/_npx/cec068fea869db4d/node_modules/@inkeep/ai-api/lib/sdks.js',
    '/Users/mdodell/.npm/_npx/cec068fea869db4d/node_modules/@inkeep/ai-api/sdk/sdk.js'
  ]
}
```

### How to reproduce

Run `npx auth secret` in the terminal.

### Expected behavior

A secret is produced.

**Comment by richardpickett** [comment]
Same, but linux.

  System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Xeon(R) W-11955M CPU @ 2.60GHz
    Memory: 43.51 GB / 62.01 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
  Browsers:
    Brave Browser: 128.1.69.153
    Chrome: 128.0.6613.84
    Chromium: 128.0.6613.113

**Comment by swikars1** [comment]
same issue

**Comment by jannomeister** [comment]
same issue
